version: '2'
services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./:/var/www:ro
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build: ./docker/php/local
        restart: always
        volumes:
            - ./:/var/www:cached
            - composer_cache:/home/docker/.composer/cache
    maria_db:
        image: mariadb
        restart: always
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        restart: always

volumes:
    composer_cache:
